### ISSUE TITLE
visualisation with sparseplane

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [samiragarwala/PlaneFormers#7]
I run prediction using 8 image, and I get the output.pkl file.

then I run:
`conda activate sparseplane `
`python viz.py --pred-file output.pkl --output-dir ./`

It returns an error:
```
/home/mrt/dev/PlaneFormers/SparsePlanes/sparsePlane/sparseplane/utils/pycococreatortools.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  contours = np.subtract(contours, 1)
Traceback (most recent call last):
  File "viz.py", line 26, in <module>
    show_camera=True, corr_list=preds[3], webvis=False)
  File "/home/mrt/dev/PlaneFormers/planeformers/figure_factory/visualize_mv.py", line 430, in save_multiple_objects
    cam_meshes = get_camera_meshes(cam_list)`
  File "/home/mrt/dev/PlaneFormers/SparsePlanes/sparsePlane/sparseplane/utils/mesh_utils.py", line 358, in get_camera_meshes
    assert len(predetermined_color) == len(camera_list)
AssertionError

**Comment by Tariq-Abuhashim** [comment]
I managed to find a fix, the maximum number of colors to plot cameras is hard coded at 5 cameras maximum.

**Comment by Tariq-Abuhashim** [comment]
I managed to find a fix, the maximum number of colors to plot cameras is hard coded at 5 cameras maximum.
```
predetermined_color = [
        [0.10196, 0.32157, 1.0],
        [1.0, 0.0667, 0.1490],
        [197/255, 181/255, 24/255],
        [73/255, 145/255, 115/255],
        [198/255, 120/255, 221/255],
    ][:len(camera_list)]
 ```
